### ISSUE TITLE
Create Arena Error

### ISSUE THREAD

**Issue by endercrest** [endercrest/ColorCube#100]
Reported by Karagra. http://pastebin.com/5VQtg81h

**Comment by endercrest** [comment]
This was an error due to unsupported version of spigot.

**Comment by Lmmb74** [comment]
But that means that you are not supporting 1.8? u.u

**Comment by endercrest** [comment]
@Lmmb74 No, currently 1.8 is not on the list of supported versions. There might be a future patch that adds support, but at this time, there are some API's this plugin uses that require a little bit more work to also add in 1.8.
