### ISSUE TITLE
Only one team on scoreboard

### ISSUE THREAD

**Issue by kamcio96** [endercrest/ColorCube#107]
Hi, when im using your plugin all players have only ```BLUE: XX``` on scoreboard sidebar. 
Paperclip 1.11.2, only ColorCube plugin, without BungeeCord

And sugesstion to support paperspigot-api title (version below 1.11):
```
        try {
            player.sendTitle(msg, "", fadeIn, stay, fadeOut);
        } catch (Throwable e) {
            player.sendTitle(Title.builder().title(msg).subtitle("").fadeIn(fadeIn).stay(stay).fadeIn(fadeOut).build());
        }
```

**Comment by endercrest** [comment]
Thanks for the suggestion, I will look into the problem. As for the suggested code I will take it into consideration.

**Comment by kamcio96** [comment]
Any updates? :stuck_out_tongue_winking_eye:

**Comment by endercrest** [comment]
Sorry, not yet. Haven't had a chance to look at it yet. This weekend I will be able to try to fix it.

**Comment by endercrest** [comment]
This issue has been fixed, this was due to a calculation error. You can download the prerelease [here](https://github.com/endercrest/ColorCube/releases/tag/V0.7.3-R0.1-SNAPSHOT)
