### ISSUE TITLE
[v0.2.8-BETA] Powerups Not Working When Stacked

### ISSUE THREAD

**Issue by PikachuPorkChops** [endercrest/ColorCube#26]
If you're giving a teammate a powerup, it'll stack with similar ones in his inventory. The powerups can't be used when in a stack.

**Comment by endercrest** [comment]
There was no easy fix for this. So I have made it so they do not stack on the pickup.

**Comment by PikachuPorkChops** [comment]
If you throw two or more of the same item down, Minecraft autostacks them. This causes them to be picked up -- already in a stack -- and the players can then not use the items.

**Comment by PikachuPorkChops** [comment]
[v0.4.0-PRE-09] This is still occurring, but occasionally this is the outcome: (https://github.com/endercrest/ColorCube/issues/52)

**Comment by endercrest** [comment]
Should no longer occur now that items can't be stacked.
