### ISSUE TITLE
Max Players

### ISSUE THREAD

**Issue by PikachuPorkChops** [endercrest/ColorCube#29]
Set the max players allowed in an arena.

**Comment by endercrest** [comment]
Do we still need this? Just set the amount of spawns and that will set the max allowed players inside the arena.

**Comment by PikachuPorkChops** [comment]
Sure, I believe what I was thinking at the time was that you'd set one spawn for every team. You can close it if you think that the way spawning is setup now is better.

**Comment by endercrest** [comment]
For now I am going to close this. As I do not think that this is relevant right now.
