### ISSUE TITLE
[v0.4.0-PRE-09] Infinite Powerup Duplication

### ISSUE THREAD

**Issue by PikachuPorkChops** [endercrest/ColorCube#52]
When powerups are thrown out of the inventory (then auto-stacked on the ground by MC) and you try to pick them up, you don't actually remove them from the ground, instead, you get an infinite amount of whatever that powerup was. All of the duplicates are usable. No errors in console.

**Comment by endercrest** [comment]
Fixed now that players can't throw items onto the ground.
