### ISSUE TITLE
[v0.4.0-PRE-09] Players Keep Powerups

### ISSUE THREAD

**Issue by PikachuPorkChops** [endercrest/ColorCube#54]
When a game is ended due to lack of players, players who obtained powerups through commands will retain them when the game is ended.

**Comment by endercrest** [comment]
Only happens when sitting beside a stack of infinte powerups on ground. This is related to #52. When infinite pickup is fix. Then this will automatically be fixed.

**Comment by endercrest** [comment]
Fixed in v0.4.0-PRE-10
