### ISSUE TITLE
Lobby Sign Variables

### ISSUE THREAD

**Issue by PikachuPorkChops** [endercrest/ColorCube#60]
Variables that can be used to customize lobby signs, providing players with live information.
%PLAYERS - Amount of players in game or in lobby
%MAX_PLAYERS - Maximum amount of players possible in that game
~~%TIME_LEFT - Time before game ends (if in lobby, then "Waiting" is displayed instead of a number)~~
%SPECTATORS - Number of spectators
%WINNING_TEAM - Team that is currently winning
%STATUS - Current status of the game ("Ingame" "Lobby" or "Resetting")

**Comment by endercrest** [comment]
I will not do TIME_LEFT. This is because this would require the sign to update every tick. This would cause lag if there are many signs. As the sign is only updated when there is a change to player size and many other things.
