### ISSUE TITLE
Economy Support

### ISSUE THREAD

**Issue by Anerak** [endercrest/ColorCube#65]
I thought of an option for economy in which it can link with other plugins. Eg: Essentials, PlayerPoints (especially the latter).
Sorry my bad English, I'm from Argentina.
Greetings;)
PD: I was using google translator

**Comment by endercrest** [comment]
That is a very good suggestion. I am surprised I have never suggested this myself. I will look into adding support to this.

**Comment by PikachuPorkChops** [comment]
Vault integration would be good too.

**Comment by endercrest** [comment]
Vault support would be what I implement as that would cover basically all basis's for economy.

**Comment by endercrest** [comment]
What would work best? Per arena reward or just a global reward?

**Comment by Anerak** [comment]
Maybe arena reward. Think that you can have one arena most difficult than other.

**Comment by endercrest** [comment]
Fair enough. I did start some work on it. But It will probably not be completed till next weekend as I have a busy school schedule during the week.
