### ISSUE TITLE
Team system

### ISSUE THREAD

**Issue by Darkool** [endercrest/ColorCube#66]
Dear Endercrest, may you add a Team System? If it not possible can you tell me If is possible add this using your source code? I mean It's if exist events to do this. thanks.

**Comment by endercrest** [comment]
Can you elaborate on what you mean? I will gladly add this feature I just need a little more information of what you are looking for.

**Comment by Darkool** [comment]
Sure, sorry about that, I when player are on lobby they could choose team (for example: RED or BLUE)
then I could be 4 vs 4 players. (2 colors).

QUESTION :How winner event works? I mean it check on finish arena all colored blocks? or it add points every change block? thanks.

**Comment by endercrest** [comment]
At this point it bases it off of every time a block is changed. It will be changed in the future. 

I can look into adding support for choosing teams. Development will pickup again when I finish school(in 2 weeks)

**Comment by Darkool** [comment]
player block place? then nothing happen If I use for example paintball guns?, I mean not count?


I can create a gui for choose team, etc , do u have a method to join player to an team? or its random?

**Comment by endercrest** [comment]
That would be my plan is to create a GUI. Just so you know I will be update my code to include documentation when I start working on the project again. If you want you can make a stab at it and make a pull request. But if you are willing to wait I plan on adding it.

**Comment by Darkool** [comment]
Sure, just tell me when you start ;)

**Comment by endercrest** [comment]
Not sure if this is what you were looking for. But as of PR #82 the spawning system has been completely rewritten, so you can now have 2-4 teams in an arena.

**Comment by endercrest** [comment]
Since arenas can now be limited to 2 or 3 teams, I am going to close this issue. Allowing players to choose teams can cause problems and I think it is best to leave it how it is. If you come up with another suggestion, please let me know and I can take them into consideration.
