### ISSUE TITLE
Scoreboard Feature to keep track team score

### ISSUE THREAD

**Issue by demonslayer147** [endercrest/ColorCube#98]
Hi, I would like to propose my suggestion about scoreboard team score management. In the original MuscleCraft map there is a little scoreboard that appear on the right side to keep track of the team score during the game. 
Thanks in advance

**Comment by endercrest** [comment]
I will see if I will try to sneak this into 0.7.1

**Comment by endercrest** [comment]
This will be in 0.7.1. Update should be available in a couple of hours.
